### ISSUE TITLE
ERROR: Kafka_Exception_Socket_EOF: Unexpected EOF while reading 4 bytes from stream

### ISSUE THREAD

**Issue by hilojack** [quipo/kafka-php#17]
My server:
 kafka 0.8.2.2 version, php5.3.9.

```
ERROR: Kafka_Exception_Socket_EOF: Unexpected EOF while reading 4 bytes from stream (no data)
#0 /root/kafka-php/src/lib/Kafka/SimpleConsumer.php(216): Kafka_Socket->read(4, true)
#1 /root/kafka-php/src/lib/Kafka/SimpleConsumer.php(182): Kafka_SimpleConsumer->getResponseSize()
#2 /root/kafka-php/src/examples/consume.php(65): Kafka_SimpleConsumer->fetch(Object(Kafka_FetchRequest))
```

**Comment by quipo** [comment]
this library only supports kafka v. 0.5 to 0.7.x
