### ISSUE TITLE
Cannot make it work with Kafka 0.8

### ISSUE THREAD

**Issue by giorgiosironi** [quipo/kafka-php#3]
Probably rightly, as the Readme says 0.6/0.7:

```
ERROR: Kafka_Exception_Socket_EOF: Unexpected EOF while reading 4 bytes from stream (no data)
#0 /root/kafka-php/src/lib/Kafka/SimpleConsumer.php(216): Kafka_Socket->read(4, true)
#1 /root/kafka-php/src/lib/Kafka/SimpleConsumer.php(182): Kafka_SimpleConsumer->getResponseSize()
#2 /root/kafka-php/src/examples/consume.php(46): Kafka_SimpleConsumer->fetch(Object(Kafka_FetchRequest))
#3 {main}
```

Is it normal?

**Comment by jippi** [comment]
bump

**Comment by krowinski** [comment]
+1

**Comment by orenorg** [comment]
Any updates on this matter?

**Comment by quipo** [comment]
Sorry, no plans to support Kafka 0.8+ with this library.
There are others available:
https://cwiki.apache.org/confluence/display/KAFKA/Clients#Clients-PHP
